import { contextBridge, ipcRenderer } from 'electron'

const api = {
  auth: {
    login: (u: string, p: string, ck: string, ci: string) => ipcRenderer.invoke('auth:login', u, p, ck, ci),
    getCaptchaSvg: () => ipcRenderer.invoke('auth:getCaptcha'),
    isFirstRun: () => ipcRenderer.invoke('auth:isFirstRun'),
    initAdmin: (u: string, p: string) => ipcRenderer.invoke('auth:initAdmin', u, p),
  },
  device: {
    list: () => ipcRenderer.invoke('device:list'),
    create: (data: unknown) => ipcRenderer.invoke('device:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('device:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('device:delete', id),
    getById: (id: string) => ipcRenderer.invoke('device:getById', id),
  },
  topology: {
    list: () => ipcRenderer.invoke('topology:list'),
    getById: (id: string) => ipcRenderer.invoke('topology:getById', id),
    create: (data: unknown) => ipcRenderer.invoke('topology:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('topology:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('topology:delete', id),
    exportJson: (id: string) => ipcRenderer.invoke('topology:exportJson', id),
    importJson: (data: string) => ipcRenderer.invoke('topology:importJson', data),
  },
  connection: {
    sshConnect: (deviceId: string) => ipcRenderer.invoke('connection:ssh', deviceId),
    telnetConnect: (deviceId: string) => ipcRenderer.invoke('connection:telnet', deviceId),
    openWeb: (url: string) => ipcRenderer.invoke('connection:openWeb', url),
    disconnect: (sessionId: string) => ipcRenderer.invoke('connection:disconnect', sessionId),
    onData: (sid: string, cb: (data: string) => void) => {
      ipcRenderer.on(`connection:data:${sid}`, (_e, data) => cb(data))
    },
    write: (sid: string, data: string) => ipcRenderer.invoke('connection:write', sid, data),
    test: (deviceId: string) => ipcRenderer.invoke('connection:test', deviceId),
  },
  ai: {
    chat: (messages: unknown[], deviceIds?: string[], sessionId?: string) => ipcRenderer.invoke('ai:chat', messages, deviceIds, sessionId),
    discoverTopology: (deviceIds: string[]) => ipcRenderer.invoke('ai:discoverTopology', deviceIds),
    getConfig: () => ipcRenderer.invoke('ai:getConfig'),
    saveConfig: (config: unknown) => ipcRenderer.invoke('ai:saveConfig', config),
    getCommandWhitelist: () => ipcRenderer.invoke('ai:getCommandWhitelist'),
    saveCommandWhitelist: (list: string[]) => ipcRenderer.invoke('ai:saveCommandWhitelist', list),
    getExecMode: () => ipcRenderer.invoke('ai:getExecMode'),
    setExecMode: (mode: string, password: string) => ipcRenderer.invoke('ai:setExecMode', mode, password),
    confirmCommand: (execId: string, approved: boolean) => ipcRenderer.invoke('ai:confirmCommand', execId, approved),
    getLogs: (limit?: number) => ipcRenderer.invoke('ai:getLogs', limit),
    getChatHistory: () => ipcRenderer.invoke('ai:getChatHistory'),
    saveMessage: (role: string, content: string, deviceId?: string | null, sessionId?: string | null) => ipcRenderer.invoke('ai:saveMessage', role, content, deviceId, sessionId),
    clearHistory: () => ipcRenderer.invoke('ai:clearHistory'),
    createSession: (title: string, deviceId?: string) => ipcRenderer.invoke('ai:createSession', title, deviceId),
    listSessions: () => ipcRenderer.invoke('ai:listSessions'),
    getSessionMessages: (sessionId: string) => ipcRenderer.invoke('ai:getSessionMessages', sessionId),
    deleteSession: (sessionId: string) => ipcRenderer.invoke('ai:deleteSession', sessionId),
    updateSessionTitle: (sessionId: string, title: string) => ipcRenderer.invoke('ai:updateSessionTitle', sessionId, title),
    getSystemLogs: (limit?: number) => ipcRenderer.invoke('ai:getSystemLogs', limit),
  },
  arp: {
    collectFromDevice: (deviceId: string) => ipcRenderer.invoke('arp:collectFromDevice', deviceId),
    collectFromAll: () => ipcRenderer.invoke('arp:collectFromAll'),
  },
  network: {
    getAll: () => ipcRenderer.invoke('network:getAll'),
    getById: (id: number) => ipcRenderer.invoke('network:getById', id),
    create: (data: unknown) => ipcRenderer.invoke('network:create', data),
    update: (data: unknown) => ipcRenderer.invoke('network:update', data),
    delete: (id: number) => ipcRenderer.invoke('network:delete', id),
    autoDiscover: () => ipcRenderer.invoke('network:autoDiscover'),
    getIPUsage: (networkId: number) => ipcRenderer.invoke('network:getIPUsage', networkId),
    getIPDetails: (networkId: number, searchIp?: string, searchMac?: string, sortBy?: string, sortOrder?: string) =>
      ipcRenderer.invoke('network:getIPDetails', networkId, searchIp, searchMac, sortBy, sortOrder),
  },
  anomaly: {
    getChanges: (unacknowledgedOnly?: boolean, limit?: number) => ipcRenderer.invoke('anomaly:getChanges', unacknowledgedOnly, limit),
    acknowledge: (id: number, notes?: string) => ipcRenderer.invoke('anomaly:acknowledge', id, notes),
    acknowledgeAll: () => ipcRenderer.invoke('anomaly:acknowledgeAll'),
    deleteChange: (id: number) => ipcRenderer.invoke('anomaly:deleteChange', id),
    deleteChanges: (ids: number[]) => ipcRenderer.invoke('anomaly:deleteChanges', ids),
    getStats: () => ipcRenderer.invoke('anomaly:getStats'),
    getBindingHistory: (ip: string) => ipcRenderer.invoke('anomaly:getBindingHistory', ip),
    getExcludedIPs: () => ipcRenderer.invoke('anomaly:getExcludedIPs'),
    addExcludedIP: (data: unknown) => ipcRenderer.invoke('anomaly:addExcludedIP', data),
    deleteExcludedIP: (id: number) => ipcRenderer.invoke('anomaly:deleteExcludedIP', id),
  },
  oui: {
    getAll: () => ipcRenderer.invoke('oui:getAll'),
    search: (keyword: string) => ipcRenderer.invoke('oui:search', keyword),
    getById: (id: number) => ipcRenderer.invoke('oui:getById', id),
    add: (data: unknown) => ipcRenderer.invoke('oui:add', data),
    addBatch: (entries: unknown[]) => ipcRenderer.invoke('oui:addBatch', entries),
    update: (data: unknown) => ipcRenderer.invoke('oui:update', data),
    delete: (id: number) => ipcRenderer.invoke('oui:delete', id),
    deleteBatch: (ids: number[]) => ipcRenderer.invoke('oui:deleteBatch', ids),
    getVendor: (mac: string) => ipcRenderer.invoke('oui:getVendor', mac),
    getAllVendors: () => ipcRenderer.invoke('oui:getAllVendors'),
    getStats: () => ipcRenderer.invoke('oui:getStats'),
  },
  export: {
    arpTable: () => ipcRenderer.invoke('export:arpTable'),
    changes: (unacknowledgedOnly?: boolean) => ipcRenderer.invoke('export:changes', unacknowledgedOnly),
    networkUsage: (networkId?: number) => ipcRenderer.invoke('export:networkUsage', networkId),
  },
  scheduler: {
    getConfig: () => ipcRenderer.invoke('scheduler:getConfig'),
    updateConfig: (data: unknown) => ipcRenderer.invoke('scheduler:updateConfig', data),
    runNow: () => ipcRenderer.invoke('scheduler:runNow'),
    getStatus: () => ipcRenderer.invoke('scheduler:getStatus'),
  },
}

contextBridge.exposeInMainWorld('api', api)
